### ISSUE TITLE
Где же ваша база данных?

### ISSUE THREAD

**Issue by nathanchere** [lexus27/php-regex#1]
OMG! почему это дерьмо не работает, когда я бегу в первый раз? Даже `npm install` и все просто делает свое собственное соединение. Где же ваша база данных?

**Comment by lexus27** [comment]
@nathanchere :D Better to have written this issue in English)

At the moment, the component version is not stable and is constantly updated, but other than that, all that passes in "commit" works quite.

Besides it will soon be unit-tests

In any case, thanks for such a delightful and funny issue :1st_place_medal:

**Comment by lexus27** [comment]
To install this component in your work environment, you should use 
`composer require lexus27/php-regex`

To contribute the component code and to the study , it is advisable to use the
`git clone https://github.com/lexus27/php-regex.git`
